Clever Linen Fox

medium

# there is a wrong require check in `executeTransaction` revert for expiration of challenge.

## Summary
there is a wrong check in `executeTransaction` revert for expiration of challenge.
## Vulnerability Detail
in contract `telcoinDistributor.sol` and in function `executeTransaction` there is a require in line 152 that checks if the challenge time period has already expired but the check actually doesn't work as intended and is broken  and does the opposite and checks after of expiration instead of not expired time, `    // Reverts if the challenge period has not expired
        require(
            block.timestamp >
                proposedTransactions[transactionId].timestamp + challengePeriod,
            "TelcoinDistributor: Challenge period has not ended"
        );`

## Impact
the require will not revert if the time period expired and allow function work fine.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L152-L156
```solidity 
    // Reverts if the challenge period has not expired
        require(
            block.timestamp >
                proposedTransactions[transactionId].timestamp + challengePeriod,
            "TelcoinDistributor: Challenge period has not ended"
        );

```
## Tool used

Manual Review

## Recommendation
- consider modifying `require` to this `<` instead of `>` 
```solidity 
    // Reverts if the challenge period has not expired
        require(
            block.timestamp <
                proposedTransactions[transactionId].timestamp + challengePeriod,
            "TelcoinDistributor: Challenge period has not ended"
        );

```